Work around an apparent JDK file deletion bug on Windows
jenkinsci/jenkins-test-harness pull request #654
Opened 2023-09-15 19:53 UTC by jglick

https://github.com/jenkinsci/workflow-cps-global-lib-http-plugin/pull/167 suppresses a couple of tests on Windows assuming they are flakes introduced by #198. In fact the failures are caused by #198 but are not flakes; I am able to reproduce https://github.com/jenkinsci/workflow-cps-global-lib-http-plugin/runs/16806834502 consistently on Windows 10 running on a VirtualBox file share, and I see no evidence of unclosed file handles or background activity in that plugin. For some reason, the `libs` subdirectory of the build directory does not get deleted the first time you call `Files.delete` on it (after deleting its children). Asking to delete `libs` again works. No other directories are affected. Using `File.delete` rather than the NIO method also deletes `libs` the first time. I suspect a bug in `WindowsFileSystemProvider.implDelete` but have not yet tried to narrow it down to a reproducible test case.

2023-09-16 10:16 UTC, timja approved these changes

2023-09-18 20:38 UTC, jglick commented
Holding off on this in the hope that I will find time to dig into why just these two tests, and no others that I know of, would cause the odd behavior.

2023-09-20 09:22 UTC, jtnord commented
couple of things.
the /lib directory sounds like it is a git clone?  
if so - perhaps a bug in jgit that is not releasing a file correctly (or perhaps caused by a bug in the code somewhere that is not closing something expected, and then leaving it to GC).
That it works in the old `io` sounds more like it is a timing issue rather than a bug in the JDK, alternatively something in pipeline still around.

https://github.com/basil/workflow-cps-global-lib-http-plugin/blob/bbab97bf7e1352cf6d0279bc788489340b1f2dbf/src/test/java/com/amadeus/jenkins/plugins/workflow/libs/HttpRetrieverIntegrationTests.java#L240-L242 and https://github.com/basil/workflow-cps-global-lib-http-plugin/blob/bbab97bf7e1352cf6d0279bc788489340b1f2dbf/src/test/java/com/amadeus/jenkins/plugins/workflow/libs/HttpRetrieverIntegrationTests.java#L274-L276 looks to be the culript or at least suspicious on the surface wrong - it is creating a stream using `Files.list` but it is not closing it, instead relying on GC.

Terminal operators do not close the underlying stream.

2023-09-20 10:32 UTC, jtnord requested changes
There is no bug to fix - the plugins test code was bad.

2023-09-20 11:08 UTC, jglick commented
> the /lib directory sounds like it is a git clone?

In this case, no, the clone happens to a shared location and then selected files are copied into the build directory with a `FilePath` method.

2023-09-20 11:08 UTC, closed without merging